=== Poonam-001/Emerging-cw2/catalog_20049412.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--declared targetNamespace-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cw="http://www.cw2.com/catalog_20049412" targetNamespace="http://www.cw2.com/catalog_20049412" elementFormDefault="qualified" attributeFormDefault="unqualified" xmlns="http://www.w3.org/2001/XMLSchema">

    <!--root element named stores-->
    <xs:element name="stores">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="store" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
<!--element store-->
    <xs:complexType name="store">
        <xs:sequence>
            <xs:element name="welcome" type="xs:string" />
            <xs:element name="store_info" />
            <xs:element name="gift_cards" />
            <xs:element name="footer" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <!--store_info element-->
    <xs:complexType name="store_info">
        <xs:sequence>
            <xs:element name="logo" />
            <xs:element name="store_name" type="xs:string" />
            <xs:element name="store_manager" type="xs:string" />
            <xs:element name="items" />
            <xs:element name="address" />
            <xs:element name="telephone_numbers" />
            <xs:element name="websites" type="xs:string" />
            <xs:element name="email" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <!--store_manager element-->
    <xs:complexType name="store_manager">
        <xs:attribute name="title" type="xs:string" use="required" />
    </xs:complexType>

    <!--items element-->
    <xs:complexType name="items">
        <xs:sequence>
            <xs:element name="item" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!--item attribute-->
    <xs:attributeGroup name="item">
        <xs:attribute name="price" type="xs:decimal" use="required" />
        <xs:attribute name="quantity" type="xs:integer" use="prohibited" />
        <xs:attribute name="item_number" type="xs:integer" use="optional" />
    </xs:attributeGroup>

    <!--address element-->
    <xs:complexType name="address">
        <xs:all>
            <xs:element name="street" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="city" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="state" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="zip" type="xs:positiveInteger" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!--telephone_numbers element-->
    <xs:complexType name="telephone_numbers">
        <xs:all>
            <xs:element name="phone" type="xs:long" minOccurs="0" maxOccurs="1" />
            <xs:element name="telephone_number" type="xs:long" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!--footer element-->
    <xs:complexType name="footer">
        <xs:all>
            <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="company" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>

    <!--gift_cards element-->
    <xs:complexType name="gift_cards">
        <xs:sequence>
            <xs:element name="c_image" />
            <xs:element name="card_details" />
            <xs:element name="validity" />
            <xs:element name="customer_category" />
            <xs:element name="number_of_users" type="xs:long" />
            <xs:element name="discount" type="xs:int" />
            <xs:element name="phone" type="xs:long" />
            <xs:element name="features" />
            <xs:element name="message" />
        </xs:sequence>
    </xs:complexType>

    <xs:attributeGroup name="gift_card">
      <xs:attribute name="id" type="xs:ID" use="required" />
      <xs:attribute name="card_type" type="xs:string" fixed="digital"/>
      <xs:attribute name="unique" type="xs:NMTOKEN" use="required" />
    </xs:attributeGroup>

    <!--card_details element-->
    <xs:complexType name="card_details">
        <xs:all>
            <xs:element name="card_name" type="xs:string" />
            <xs:element name="cost" type="xs:string" />
            <xs:element name="type" type="xs:string" />
        </xs:all>
    </xs:complexType>

    <xs:complexType name="cost">
        <xs:attribute name="unit" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="validity">
        <xs:all>
            <xs:element name="issue_date" type="xs:date" />
            <xs:element name="expire_date" type="xs:date" />
        </xs:all>
    </xs:complexType>

    <!--customer_category element with attribute-->
    <xs:complexType name="customer_category">
        <xs:attribute name="category" type="xs:string" use="required" />
    </xs:complexType>

    <!--feature_number element-->
    <xs:complexType name="features">
        <xs:sequence>
            <xs:element name="heading" type="xs:string" />
            <xs:element name="feature" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <!--providing enumeration value to the feature_number element-->
    <xs:complexType name="feature">
        <xs:attribute name="feature_number" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:enumeration value="1" />
                    <xs:enumeration value="2" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>
    
    <xs:complexType name="message">
        <xs:sequence>
            <xs:element name="title" type="xs:string" />
            <xs:element name="description" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <!--providing enumeration value to the description_number element-->
    <xs:complexType name="description">
        <xs:attribute name="description_number" use="optional">
            <xs:simpleType>
                <xs:restriction base="xs:int">
                    <xs:enumeration value="1" />
                    <xs:enumeration value="2" />
                    <xs:enumeration value="3" />
                    <xs:enumeration value="4" />
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

</xs:schema>

=== Poonam-001/Emerging-cw2/catalog_20049412.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet href="catalog_20049412.css" cw:type="text/css"?><!--linked to CSS-->
<!--
    Name: Poonam Singh Yadav
    Londonmet ID: 20049412
    CollegeID: np01cp4s210213
    Date: 3/31/2022
-->
<!--linked to xsd, css and given the schema location-->
<cw:stores xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns:cw="http://www.cw2.com/catalog_20049412" xs:schemaLocation="http://www.cw2.com/catalog_20049412 catalog_20049412.xsd">
<!--Complex type because it contains attribute and child element-->
<cw:store id="s001">
        <!--Simple type because it contains simple text-->
        <cw:welcome>Welcome to the Store</cw:welcome>
        <cw:store_info>
            <!--Empty element because it does not contain attribute or child element or simple text-->
            <cw:logo />
            <cw:store_name>Evergreen Store</cw:store_name>
            <!--Complex type because it contains attribute and simple text-->
            <cw:store_manager title="Mr">John Clover</cw:store_manager>
            <cw:items>
                <!--entity reference for & symbol-->
                <item price="$20" quantity="50" item_number="1">Drinks &amp; Snacks</item>
                <item price="$50" quantity="20" item_number="2">Colors</item>
                <item price="$100" quantity="25" item_number="3">Jwellery</item>
                <item price="$30" quantity="35" item_number="4">Petrollium</item>
            </cw:items>
            <cw:address>
                <street>212 East Advent St.</street>
                <city>Cutler</city>
                <state>MO</state>
                <zip>32815</zip>
            </cw:address>
            <cw:telephone_numbers>
                <phone>2043134135</phone>
                <telephone_number>3423524520</telephone_number>
            </cw:telephone_numbers>
            <cw:website>www.evergreen.com</cw:website>
            <cw:email>evergreenstore2341@gmail.com</cw:email>
        </cw:store_info>

        <cw:gift_cards>
            <!--complex type because it contains multiple attributes and child elements-->
            <cw:gift_card id="GF-C001" card_type="digital" unique_code="32:86-00">
                <cw:c_image />
                <cw:card_details>
                    <cw:card_name>Colouring Course Gift Card</cw:card_name>
                    <cw:cost unit="$">50.35</cw:cost>
                    <cw:type>Debit</cw:type>
                </cw:card_details>
                <cw:validity>
                    <cw:issue_date>5-25-2020</cw:issue_date>
                    <cw:expire_date>5-25-2025</cw:expire_date>
                </cw:validity>
                <!--complex type because it contains an attribute-->
                <cw:customer_category category="VIP"/>
                <cw:number_of_users>60000</cw:number_of_users>
                <cw:discount>13</cw:discount>
                <cw:phone>1057357365</cw:phone>
                <cw:features>
                    <cw:heading>Features</cw:heading>
                    <cw:feature feature_number="1"> You can pay with the card to related store.</cw:feature>
                    <cw:feature feature_number="2"> No need to carry cash and no fear of lost or theft.</cw:feature>
                </cw:features>
                <cw:message>
                    <cw:title>Terms and conditions</cw:title>
                    <cw:descriptions>
                        <description description_number="1"> This card is non transferable and will remain the property of the mart.</description>
                        <description description_number="2"> It must be returned upon request.</description>
                        <description description_number="3"> In case of lost or theft of the card must be reported immediately.</description>
                        <description description_number="4"> Please return the card to the related store if found.</description>
                    </cw:descriptions>
                </cw:message>
            </cw:gift_card>

            <cw:gift_card id="GF-C002" card_type="digital" unique_code="43:22-55">
                <cw:cs_image />
                <cw:card_details>
                    <cw:card_name>Cosmetics Gift Card</cw:card_name>
                    <cw:cost unit="$">550</cw:cost>
                    <cw:type>Credit</cw:type>
                </cw:card_details>
                <cw:validity>
                    <cw:issue_date>10-20-2020</cw:issue_date>
                    <cw:expire_date>10-31-2026</cw:expire_date>
                </cw:validity>
                <cw:customer_category category=" New"/>
                <cw:number_of_users>6000</cw:number_of_users>
                <cw:phone>5173573451</cw:phone>
                <cw:features>
                    <cw:heading>Features</cw:heading>
                    <cw:feature feature_number="1"> You can pay with the card to related store.</cw:feature>
                    <cw:feature feature_number="2"> No need to carry cash and no fear of lost or theft.</cw:feature>
                </cw:features>
                <cw:message>
                    <cw:title>Terms and conditions</cw:title>
                    <cw:descriptions>
                        <description description_number="1"> This card is non transferable and will remain the property of the mart.</description>
                        <description description_number="2"> It must be returned upon request.</description>
                        <description description_number="3"> In case of lost or theft of the card must be reported immediately.</description>
                        <description description_number="4"> Please return the card to the related store if found.</description>
                    </cw:descriptions>
                </cw:message>
            </cw:gift_card>

            <cw:gift_card id="GF-C003" card_type="digital" unique_code="01:64-35">
                <cw:j_image />
                <cw:card_details>
                    <cw:card_name>Jwellery Gift Card</cw:card_name>
                    <cw:cost unit="$">600</cw:cost>
                    <cw:type>Credit</cw:type>
                </cw:card_details>
                <cw:validity>
                    <cw:issue_date>5-13-2022</cw:issue_date>
                    <cw:expire_date>3-31-2027</cw:expire_date>
                </cw:validity>
                <cw:customer_category category="Regular"/>
                <cw:number_of_users>80000</cw:number_of_users>
                <cw:discount>12</cw:discount>
                <cw:phone>2537350173</cw:phone>
                <cw:features>
                    <cw:heading>Features</cw:heading>
                    <cw:feature feature_number="1"> You can pay with the card to related store.</cw:feature>
                    <cw:feature feature_number="2"> No need to carry cash and no fear of lost or theft.</cw:feature>
                </cw:features>
                <cw:message>
                    <cw:title>Terms and conditions</cw:title>
                    <cw:descriptions>
                        <description description_number="1"> This card is non transferable and will remain the property of the mart.</description>
                        <description description_number="2"> It must be returned upon request.</description>
                        <description description_number="3"> In case of lost or theft of the card must be reported immediately.</description>
                        <description description_number="4"> Please return the card to the related store if found.</description>
                    </cw:descriptions>
                </cw:message>
            </cw:gift_card>

            <cw:gift_card id="GF-C004" card_type="digital" unique_code="93:39-64">
                <cw:l_image />
                <cw:card_details>
                    <cw:card_name>Leather Gift Card</cw:card_name>
                    <cw:cost unit="$">95</cw:cost>
                    <cw:type>Debit</cw:type>
                </cw:card_details>
                <cw:validity>
                    <cw:issue_date>2-15-2021</cw:issue_date>
                    <cw:expire_date>3-31-2026</cw:expire_date>
                </cw:validity>
                <cw:customer_category category="Loyal"/>
                <cw:number_of_users>70000</cw:number_of_users>
                <cw:phone>0157356573</cw:phone>
                <cw:features>
                    <cw:heading>Features</cw:heading>
                    <cw:feature feature_number="1"> You can pay with the card to related store.</cw:feature>
                    <cw:feature feature_number="2"> No need to carry cash and no fear of lost or theft.</cw:feature>
                </cw:features>
                <cw:message>
                    <cw:title>Terms and conditions</cw:title>
                    <cw:descriptions>
                        <description description_number="1"> This card is non transferable and will remain the property of the mart.</description>
                        <description description_number="2"> It must be returned upon request.</description>
                        <description description_number="3"> In case of lost or theft of the card must be reported immediately.</description>
                        <description description_number="4"> Please return the card to the related store if found.</description>
                    </cw:descriptions>
                </cw:message>
            </cw:gift_card>

            <cw:gift_card id="GF-C005" card_type="digital" unique_code="31:03-77">
                <cw:L_image />
                <cw:card_details>
                    <cw:card_name>Liquor Gift Card</cw:card_name>
                    <cw:cost unit="$">800</cw:cost>
                    <cw:type>Debit</cw:type>
                </cw:card_details>
                <cw:validity>
                    <cw:issue_date>1-31-2022</cw:issue_date>
                    <cw:expire_date>3-31-2026</cw:expire_date>
